#!/bin/sh
name=$1
fb=$2
linkedin=$3

mkdir "$name `date`"
cd "$name `date`"

mkdir -p about_me/personal
echo "https://www.facebook.com/$fb" > about_me/personal/facebook.txt

mkdir -p about_me/professional
echo "https://www.linkedin.com/in/$linkedin" > about_me/professional/linkedin.txt

mkdir -p my_friends
curl https://gist.githubusercontent.com/tegarimansyah/e91f335753ab2c7fb12815779677e914/raw/94864388379fecee450fde26e3e73bfb2bcda194/list%2520of%2520my%2520friends.txt -o my_friends/list_of_my_friends.txt
echo "" >> my_friends/list_of_my_friends.txt

mkdir -p my_system_info
ping -c 3 google.com > my_system_info/internet_connection.txt
echo "My username:" `whoami` > my_system_info/about_this_laptop.txt
echo "With host:" `uname -a` >> my_system_info/about_this_laptop.txt
